esphome:
  name: dehumidifier
  friendly_name: Dehumidifier
  platformio_options:
    board_build.flash_mode: dio
    board_build.mcu: esp32c3
  on_boot:
    priority: -100
    then:
      - script.execute: mode_thaw

esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: arduino
    platform_version: 5.4.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: YOUR_KEY

ota:
  password: YOUR_PASSWORD

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dehumidifier Fallback Hotspot"
    password: YOUR_PASSWORD

captive_portal:

i2c:
  sda: GPIO6
  scl: GPIO7
  scan: True

switch:
  - platform: gpio
    pin: GPIO5
    restore_mode: ALWAYS_OFF
    internal: True
    id: peltier_mosfet

output:
  - platform: sigma_delta_output
    id: peltier
    update_interval: 400ms
    min_power: 0.0
    max_power: 1.0
    turn_on_action:
      then:
        - switch.turn_on: peltier_mosfet
    turn_off_action:
      then:
        - switch.turn_off: peltier_mosfet

external_components:
  - source: github://nrandell/dallasng

dallasng:
  - pin: GPIO8
    update_interval: 1.5s

sensor:
  - platform: dallasng
    index: 0
    name: Cold side temperature
    id: cold_temperature
  - platform: aht10
    variant: AHT20
    temperature:
      name: "Air Temperature"
      id: air_temperature
    humidity:
      name: "Air Humidity"
      id: air_humidity
    update_interval: 5s
  - platform: pid
    name: Peliter PWM
    type: COOL
  - platform: pid
    name: "[P]ID"
    type: PROPORTIONAL
  - platform: pid
    name: "P[I]D"
    type: INTEGRAL
  - platform: pid
    name: "PI[D]"
    type: DERIVATIVE

script:
  - id: mode_normal
    then:
      - climate.control:
          id: pid_climate
          target_temperature: -0.5 °C
      - delay: 15min
      - script.execute: mode_thaw
  - id: mode_thaw
    then:
      - climate.control: 
          id: pid_climate
          target_temperature: 2.0 °C
      - delay: 5min
      - script.execute: mode_normal

climate:
  - platform: pid
    id: pid_climate
    name: Thermostat
    sensor: cold_temperature
    default_target_temperature: -0.5 °C
    cool_output: peltier
    visual:
      min_temperature: -4 °C
      max_temperature: 10 °C
    control_parameters:
      kp: 0.3
      ki: 0.006
      kd: 1.7
      output_averaging_samples: 2
      derivative_averaging_samples: 6
    # deadband_parameters:
    #   threshold_high: 0.1°C
    #   threshold_low: -0.1°C
    
button:
  - platform: template
    name: Climate PID autotune
    on_press:
      - climate.pid.autotune: pid_climate
    